
-- DIMENSION TABLE LOCATION
CREATE OR REPLACE TABLE LOCATION(
    LOCATION_ID INT AUTOINCREMENT,
    ADDRESS STRING,
    COUNTY STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PRIMARY KEY(LOCATION_ID)

);

--DIMENSION TABLE PROPERTY
CREATE OR REPLACE TABLE PROPERTY(
    PROPERTY_ID INT AUTOINCREMENT,
    PROPERTYTYPE STRING,
    BATHROOMS STRING,
    BEDROOMS STRING,
    BER STRING,
    CATEGORY STRING,
    PRIMARY KEY (PROPERTY_ID)
);

--CREATE TABLE AGENT 

CREATE OR REPLACE TABLE AGENT(
    AGENT_ID INT,
    AGENT_NAME STRING,
    AGENT_BRANCH STRING,
    AGENT_SELLER_TYPE STRING,
    PRIMARY KEY (AGENT_NAME)
);

-- CREATE TABLE SALES
CREATE OR REPLACE TABLE SALES(
    SALE_ID INT,
    LOCATION_ID INT,
    PROPERTY_ID INT,
    AGENT_NAME STRING,
    SALETYPE STRING,
    MONTHLY_PRICE STRING,
    PRICE FLOAT,
    PUBLISH_DATE TIMESTAMP,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID),
    FOREIGN KEY (AGENT_NAME) REFERENCES AGENT(AGENT_NAME),
    PRIMARY KEY (SALE_ID)
);