-- DIMENSION TABLE LOCATION
CREATE OR REPLACE TABLE LOCATION(
    LOCATIONID INT START 1 AUTOINCREMENT 1,
    ADDRESS STRING,
    COUNTY STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PRIMARY KEY(LOCATIONID)

);

--DIMENSION TABLE PROPERTY
CREATE OR REPLACE TABLE PROPERTY(
    PROPERTYID INT AUTOINCREMENT START 1 INCREMENT 1,
    PROPERTYTYPE STRING,
    BATHROOMS STRING,
    BEDROOMS STRING,
    BER STRING,
    CATEGORY STRING,
    PRIMARY KEY (PROPERTYID)
);

--CREATE TABLE AGENT 

CREATE OR REPLACE TABLE AGENT(
    AGENTID INT;
    AGENT_BRANCH STRING,
    AGENT_NAME STRING,
    AGENT_SELLER_TYPE STRING,
    PRIMARY KEY (AGENTID INT)
);

-- CREATE TABLE SALES
CREATE OR REPLACE TABLE SALES(
    SALEID INT,
    LOCATIONID INT,
    PROPERTYID INT,
    AGENTID INT,
    SALETYPE STRING,
    MONTHLY_PRICE STRING,
    PRICE FLOAT,
    PUBLISH_DATE TIMESTAMP,
    FOREIGN KEY (LOCATIONID) REFERENCES LOCATION(LOCATIONID),
    FOREIGN KEY (PROPERTYID) REFERENCES PROPERTY(PROPERTYID),
    FOREIGN KEY (AGENTID) REFERENCES AGENT(AGENTID),
    PRIMARY KEY SALEID
);

